### ISSUE TITLE
About informations are not complete, not updated...

### ISSUE THREAD

**Issue by Neustradamus** [xmpp-observatory/xmppoke-frontend#3]
In about.php, informations, links are old.

Originaly developed by xnyphs:
- https://bitbucket.org/xnyhps/xmppoke
- https://bitbucket.org/xnyhps/xmppoke-frontend

But now, you are actual developers...

**Comment by guusdk** [comment]
Please provide a PR to fix this issue.

**Comment by Neustradamus** [comment]
One year ago:
- https://github.com/xmpp-observatory/xmppoke-frontend/commit/5b17a47876369eb5247477b4b6e67111921b3e55
