### ISSUE TITLE
Retest should have a confirm step

### ISSUE THREAD

**Issue by Zash** [xmpp-observatory/xmppoke-frontend#5]
On individual result pages, after a test has completed, there is a Retest link that goes to `https://xmpp.net/submit.php?domain=DOMAIN&type=server` which queues a new test of the same domain simply by visiting it. This makes it highly likely that random web crawlers trigger new tests via GET requests. Ideally this should require a POST of some sort.

**Comment by guusdk** [comment]
Although there's no explicit confirm step, submitting now requires a POST request.
