### ISSUE TITLE
XMPP.net is down in this moment

### ISSUE THREAD

**Issue by Neustradamus** [xmpp-observatory/xmppoke-frontend#8]
XMPP.net is down in this moment

**Comment by Zash** [comment]
Some info about the incident can be found here:
https://mastodon.technology/@mattj/103866354735451821

**Comment by Neustradamus** [comment]
@Zash: Thanks for your your link but xmpp.net does not work since several months.

**Comment by intika** [comment]
Nothing new... but this is discussed [here](https://www.reddit.com/r/xmpp/comments/6346dp/whats_wrong_with_xmppnet/) as well
